# Generated by Django 3.2.4 on 2021-06-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210623_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstapp.cart'),
        ),
    ]
